// app/pages/articles/index.vue
<template>
  <LayoutHeader
    :title="$t('articles.title') + (tag ? ` (${tag})` : '')"
    :intro="$t('articles.intro')"
  >
    <div v-if="tag" class="flex justify-center">
      <nuxt-link
        href="/articles/"
        type="button"
        class="text-second-900 ring-second-300 hover:bg-second-50 dark:ring-second-700 -mt-5 rounded bg-white px-2 py-1 text-sm font-semibold shadow-sm ring-1 ring-inset dark:bg-white/10 dark:text-white dark:hover:bg-white/20"
      >
        {{ $t('articles.return_overview') }}
      </nuxt-link>
    </div>

    <nav>
      <ul
        class="border-second-200 dark:border-second-500 mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none"
      >
        <template v-for="article of list" :key="article.id">
          <li
            v-if="
              article.path.startsWith('/articles/') &&
              article.published &&
              (!tag || (article.tags ?? []).includes(tag))
            "
          >
            <ArticlePreview
              :title="article.title!"
              :href="article.path!"
              :cover="
                article.cover
                  ? joinURL('/articles', 'covers', article.cover)
                  : ''
              "
              :date="article.date"
              :description="article.description"
              :tags="article.tags ?? []"
            />
          </li>
        </template>
      </ul>
    </nav>
  </LayoutHeader>
</template>

<script setup lang="ts">
import { joinURL } from 'ufo';
import type { Collections } from '@nuxt/content';

definePageMeta({
  layout: 'article',
});

const { locale } = useI18n();
const tag = computed(() => (useRoute().query.tag ?? '') as string);

const { data: list } = await useAsyncData(
  () => {
    const collection = ('content_' + locale.value) as keyof Collections;
    return queryCollection(collection)
      .select(
        'id',
        'title',
        'description',
        'path',
        'date',
        'tags',
        'cover',
        'published',
      )
      .order('date', 'DESC')
      .all();
  },
  { watch: [locale, tag] },
);
</script>

// src/routes/[[lang=lang]]/articles/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import Header from '$lib/components/layout/Header.svelte';
  import ArticlePreview from '$lib/components/article/ArticlePreview.svelte';
  import Search from '$lib/components/article/Search.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import NewsletterForm from '$lib/components/NewsletterForm.svelte';
  import { getI18n } from '$lib/i18n/context.svelte';

  let { data } = $props();
  const i18n = getI18n();

  let query = $state('');
  let matches = $state<string[] | null>(null);
  const shown = $derived(
    matches === null
      ? data.articles
      : matches
          .map((slug) => data.articles.find((a) => a.slug === slug))
          .filter((a) => a !== undefined),
  );
</script>

<SeoHead title={i18n.t('nav.articles')} description={i18n.t('articles.intro')} />

<Header title={i18n.t('articles.title')} intro={i18n.t('articles.intro')}>
  <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
    <div class="flex flex-wrap gap-1 text-sm">
      {#each data.tags as tag (tag.slug)}
        <Badge content="{tag.tag} ({tag.count})" href={i18n.path(`/articles/tags/${tag.slug}`)} />
      {/each}
    </div>
    <div class="sm:w-72">
      <Search bind:query onresults={(r) => (matches = r)} />
    </div>
  </div>

  <nav>
    {#if shown.length === 0}
      <p class="mt-10 text-center text-second-600 dark:text-second-400">
        {i18n.t('articles.search.no_results')}
      </p>
    {:else}
      <ul
        class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-second-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none dark:border-second-500"
      >
        {#each shown as article (article.slug)}
          <li><ArticlePreview {article} /></li>
        {/each}
      </ul>
    {/if}
  </nav>

  <div class="mt-16">
    <NewsletterForm />
  </div>
</Header>
