// src/routes/[[lang=lang]]/articles/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import Header from '$lib/components/layout/Header.svelte';
  import ArticlePreview from '$lib/components/article/ArticlePreview.svelte';
  import Search from '$lib/components/article/Search.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import NewsletterForm from '$lib/components/NewsletterForm.svelte';
  import { getI18n } from '$lib/i18n/context.svelte';

  let { data } = $props();
  const i18n = getI18n();

  let query = $state('');
  let matches = $state<string[] | null>(null);
  const shown = $derived(
    matches === null
      ? data.articles
      : matches
          .map((slug) => data.articles.find((a) => a.slug === slug))
          .filter((a) => a !== undefined),
  );
</script>

<SeoHead title={i18n.t('nav.articles')} description={i18n.t('articles.intro')} />

<Header title={i18n.t('articles.title')} intro={i18n.t('articles.intro')}>
  <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
    <div class="flex flex-wrap gap-1 text-sm">
      {#each data.tags as tag (tag.slug)}
        <Badge content="{tag.tag} ({tag.count})" href={i18n.path(`/articles/tags/${tag.slug}`)} />
      {/each}
    </div>
    <div class="sm:w-72">
      <Search bind:query onresults={(r) => (matches = r)} />
    </div>
  </div>

  <nav>
    {#if shown.length === 0}
      <p class="mt-10 text-center text-second-600 dark:text-second-400">
        {i18n.t('articles.search.no_results')}
      </p>
    {:else}
      <ul
        class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-second-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none dark:border-second-500"
      >
        {#each shown as article (article.slug)}
          <li><ArticlePreview {article} /></li>
        {/each}
      </ul>
    {/if}
  </nav>

  <div class="mt-16">
    <NewsletterForm />
  </div>
</Header>

// src/pages/articles/index.vue
<template>
  <LayoutHeader :title="$t('articles.title')" :intro="$t('articles.intro')">
    <nav>
      <ContentList :path="$i18n.locale + '/articles'" v-slot="{ list }">
        <ul
          class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-second-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3 dark:border-second-500"
        >
          <li v-for="article of list" :key="article._path">
            <ArticlePreview
              :title="article.title"
              :href="article._path.replace(`/${$i18n.locale}`, '')"
              :date="article.date"
              :datetime="article.datetime"
              :description="article.description"
              :tags="article.tags"
            />
          </li>
        </ul>
      </ContentList>
    </nav>
  </LayoutHeader>
</template>
