// app/components/modal/index.vue
<template>
  <TransitionRoot as="template" :show="open">
    <Dialog as="div" class="relative z-10 break-words" @close="hide()">
      <TransitionChild
        as="template"
        enter="ease-out duration-300"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="ease-in duration-200"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div
          class="bg-second-500 bg-opacity-75 dark:bg-second-900 dark:bg-opacity-75 fixed inset-0 transition-opacity"
        />
      </TransitionChild>

      <div class="fixed inset-0 z-10 overflow-y-auto">
        <div
          :class="[
            'flex min-h-full justify-center p-4 text-center sm:p-0',
            place_top ? 'items-start' : 'items-end sm:items-center',
          ]"
        >
          <TransitionChild
            as="template"
            enter="ease-out duration-300"
            enter-from="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            enter-to="opacity-100 translate-y-0 sm:scale-100"
            leave="ease-in duration-200"
            leave-from="opacity-100 translate-y-0 sm:scale-100"
            leave-to="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          >
            <DialogPanel
              class="bg-second-50 dark:bg-second-900 relative w-full transform rounded-lg px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6 dark:text-white"
            >
              <slot />
              <div v-if="!hide_close" class="mt-5 sm:mt-6">
                <button
                  type="button"
                  class="bg-second-600 hover:bg-second-700 focus-visible:outline-second-600 dark:bg-second-800 inline-flex w-full justify-center rounded-md px-3 py-2 text-sm font-semibold text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2"
                  @click="hide()"
                >
                  Close
                </button>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script lang="ts">
import {
  Dialog,
  DialogPanel,
  TransitionChild,
  TransitionRoot,
} from '@headlessui/vue';
import { defineComponent, ref } from 'vue';

export default defineComponent({
  components: {
    Dialog,
    DialogPanel,
    TransitionChild,
    TransitionRoot,
  },
  props: {
    place_top: {
      type: Boolean,
      default: false,
    },
    hide_close: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    return {
      open: ref(false),
    };
  },
  methods: {
    show() {
      this.open = true;
    },
    hide() {
      this.open = false;
    },
  },
});
</script>

// src/lib/components/Modal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getI18n } from '$lib/i18n/context.svelte';

  let {
    open = $bindable(false),
    placeTop = false,
    hideClose = false,
    children,
  }: { open?: boolean; placeTop?: boolean; hideClose?: boolean; children: Snippet } = $props();

  const i18n = getI18n();
  let dialog = $state<HTMLDialogElement>();

  $effect(() => {
    if (!dialog) return;
    if (open && !dialog.open) dialog.showModal();
    else if (!open && dialog.open) dialog.close();
  });

  function onBackdropClick(e: MouseEvent) {
    if (e.target === dialog) open = false;
  }
</script>

<dialog
  bind:this={dialog}
  onclose={() => (open = false)}
  onclick={onBackdropClick}
  class={[
    'fixed inset-0 z-50 m-0 h-full max-h-none w-full max-w-none bg-second-500/75 bg-transparent p-4 text-left break-words backdrop:bg-transparent open:flex sm:p-0 dark:bg-second-900/75',
    placeTop ? 'items-start' : 'items-end sm:items-center',
    'justify-center',
  ]}
>
  <div
    class="relative w-full transform rounded-lg bg-second-50 px-4 pt-5 pb-4 text-second-900 shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6 dark:bg-second-900 dark:text-white"
  >
    {@render children()}
    {#if !hideClose}
      <div class="mt-5 sm:mt-6">
        <button
          type="button"
          class="inline-flex w-full justify-center rounded-md bg-second-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-second-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-second-600 dark:bg-second-800"
          onclick={() => (open = false)}
        >
          {i18n.t('common.modal.close')}
        </button>
      </div>
    {/if}
  </div>
</dialog>
